---
ui:
  env:
    - name: BACKEND_URL
      value: "http://support-bot.support-bot-extended:8080"
    - name: AUTH_SECRET
      value: "extended-test-secret-not-for-production-use"
    - name: NEXTAUTH_URL
      value: "http://support-bot-ui:3000"
