---
ui:
  env:
    - name: BACKEND_URL
      value: "http://mock-backend:8080"
    - name: NEXTAUTH_SECRET
      value: ""
    - name: NEXTAUTH_URL
      value: ""
    - name: AZURE_AD_CLIENT_ID
      value: ""
    - name: AZURE_AD_CLIENT_SECRET
      value: ""
    - name: AZURE_AD_TENANT_ID
      value: ""
    - name: GOOGLE_CLIENT_ID
      value: ""
    - name: GOOGLE_CLIENT_SECRET
      value: ""
