apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "support-bot-nft-tests.fullname" . }}
  labels:
    {{- include "support-bot-nft-tests.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  parallelism: {{ .Values.job.parallelism }}
  completions: {{ .Values.job.completions }}
  template:
    metadata:
      labels:
        {{- include "support-bot-nft-tests.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nft-tests
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICE_ENDPOINT
              value: "http://support-bot:8080"
            - name: JAVA_OPTS
              value: "-Xms2250m -Xmx2250m -Djava.util.prefs.userRoot=/tmp/java-prefs"
          ports:
            - name: slack
              containerPort: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nft-reports
              mountPath: /mnt/nft-reports
      volumes:
        - name: tmp
          emptyDir: {}
{{- if .Values.reports.pvc.enabled }}
        - name: nft-reports
          persistentVolumeClaim:
            claimName: {{ include "support-bot-nft-tests.fullname" . }}-reports
{{- else }}
        - name: nft-reports
          emptyDir: {}
{{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
