security:
  test-bypass:
    enabled: true

spring:
  cloud:
    azure:
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
enums:
  escalation-teams:
    - label: core
      code: core
      slack-group-id: S08948NBMED
platform-integration:
  enabled: true
  azure:
    enabled: true
  static-user:
    enabled: false
  teams-scraping:
    static:
      enabled: false
    core-platform:
      enabled: false
    k8s-generic:
      enabled: true
      config:
        api-version: v1
        kind: ConfigMap
        namespace: support-bot-integration
        filter:
          name-regexp: ^tenant-.*
          label-selector: null
        teamName:
          cel-expression: resource.data.name
        groupRef:
          cel-expression: resource.data.groupRef
