name: support-bot Monitoring

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Makefile'
      - 'api/k8s/dashboard/**'
      - '.github/workflows/support-bot-monitoring.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'Makefile'
      - 'api/k8s/dashboard/**'
      - '.github/workflows/support-bot-monitoring.yaml'

permissions:
  contents: write
  id-token: write

jobs:
  version:
    uses: coreeng/p2p/.github/workflows/p2p-version.yaml@v1
    with:
      version-prefix: v
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-monitoring:
    needs: [version]
    uses: coreeng/p2p/.github/workflows/p2p-execute-command.yaml@v1
    secrets:
      env_vars: ${{ secrets.env_vars }}
    with:
      github_env: gcp-dev
      app-name: support-bot
      subnamespace: grafana
      version: ${{ needs.version.outputs.version }}
      command: monitoring-deploy
      working-directory: ./
